### ISSUE TITLE
Default to indent using spaces in Sublime

### ISSUE THREAD

**Issue by tedmiston** [riot/syntax-highlight#3]
Hi Cris — Thanks for making this Sublime package.  It's super helpful when getting started with Riot.

In my usage with ST3, I've noticed that the package defaults to tab indent for `.tag` files.

Of course this can be overridden with syntax-specific settings by adding the following to `User/TAG.sublime-settings`:

```
{
    "tab_size": 2,
    "translate_tabs_to_spaces": true
}
```

(To open that file, open any `.tag`, then click `Preferences > Settings – Syntax Specific`.)

However, since two-space indent is the norm in official examples, it seems like this could be a reasonable default for the package's `Preferences.sublime-settings` so that every Sublime user doesn't have to do the same thing.  What do you think?

**Comment by crisward** [comment]
Thanks for the suggestion, and sorry for not replying sooner. I agree that 2 spaces is how I like stuff to be laid out and official examples do too. But the compiler will work with tabs, and some people just love their tabs.

You can set this up in sublime in your own preferences and it'll work just for you.

Do you know if sublime uses the syntax settings or your own settings by default? I'd hate to annoy lots of tab lovers by forcing them to use spaces.

**Comment by crisward** [comment]
I'll close this I'm sure everyone can set there own tab prefs.

**Comment by tedmiston** [comment]
Looks like I missed your reply somehow.  To answer the question you asked, I believe the chain of preferences in Sublime is: Sublime defaults --> Language prefs --> User prefs --> Project prefs.
