### ISSUE TITLE
Preserving existing indents

### ISSUE THREAD

**Issue by enjibby** [riot/syntax-highlight#8]
I prefer using 2 spaces instead of tabs for my code but, as I'm often editing shared projects, I wish to minimise my diffs when committing to source control.

Is there any way to separate the functionality of the "translate_tabs_to_spaces" setting such that any code I write personally indents using spaces, but when I'm adjusting indents on other user's code or pasting code from other sources that it preserves any tab characters that already exist?

**Comment by crisward** [comment]
This is a setting in your editor and isn't controlled by a syntax highlighter (though you've probably already worked that out)
