### ISSUE TITLE
Setting for default grammar for new file.

### ISSUE THREAD

**Issue by ejnaren** [riot/syntax-highlight#9]
I would like to suggest a setting for defining which grammar to be used on creating new files.
Now it defaults to Jade/Pug and there is no way to specify to only use HTML.

Awesome work for everything else!
Best regards.

**Comment by GianlucaGuarini** [comment]
which editor are you using? I am sure it could be automatically configured directly in your editor

**Comment by ejnaren** [comment]
Sorry for the late respons here.

Yes, I guessed it might fall between two chairs here.
Im using Atom. Im not sure how to configure it in the grammar settings of Atom but i can ask in the appropriate forum on their side.

Thanks.

**Comment by GianlucaGuarini** [comment]
cool let me know if i could help you on anything
